"""Add UserRole Enum

Revision ID: 7d5ed643e8ea
Revises: 52bd256eb2b6
Create Date: 2026-08-02 15:54:28.056406

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7d5ed643e8ea'
down_revision: str | Sequence[str] | None = '52bd256eb2b6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Khởi tạo kiểu Enum trong PostgreSQL trước khi đổi cột
    userrole_enum = sa.Enum('ADMIN', 'STAFF', 'USER', name='userrole')
    userrole_enum.create(op.get_bind(), checkfirst=True)

    # Chuyển đổi dữ liệu cột (nếu có cột đang là VARCHAR) - Sử dụng USING để ép kiểu
    op.execute("ALTER TABLE users ALTER COLUMN role TYPE userrole USING role::userrole")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE users ALTER COLUMN role TYPE VARCHAR(50) USING role::VARCHAR(50)")
    userrole_enum = sa.Enum('ADMIN', 'STAFF', 'USER', name='userrole')
    userrole_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
